FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -q && apt-get install -qy \
    git \
    biber \
    texlive \
    texlive-bibtex-extra \
    texlive-lang-czechslovak \
    texlive-xetex \
    texlive-fonts-recommended \
    lmodern

WORKDIR /root/texmf/tex/latex

RUN git clone https://github.com/michal-h21/biblatex-iso690

WORKDIR /project
VOLUME /project

COPY entrypoint.sh /bin/pdf_create

ENTRYPOINT [ "pdf_create" ]
